#!/usr/bin/python2.7
from hosted import device, node, config
config.restart_on_update()

counter = 0
device.gpio.monitor(config.pin)
for (pin, state) in device.gpio.poll_forever():
    if state is True:
        counter += 1
        node.send('/counter:%d' % counter)
